import type { Job } from "../lib/types";

// 岗位种子库 —— 字段结构对齐真实招聘平台 JD（标题/技能/薪资/经验/职责）
// 覆盖学生高频领域：互联网研发、产品运营、设计、市场、人力、金融、销售、
// 教育、客服、供应链、行政、医疗等，城市覆盖一线及新一线 + 远程
export const seedJobs: Job[] = [
  {
    id: "job-001",
    title: "后端开发工程师（校招）",
    company: "云启科技",
    category: "互联网研发",
    location: "杭州",
    salary: "15-25K·14薪",
    experience: "应届",
    skills: ["Java", "Spring Boot", "MySQL", "Redis", "微服务", "分布式"],
    description:
      "负责核心业务系统的后端开发与维护；参与高并发服务的设计与优化；编写高质量、可测试的代码。要求：计算机相关专业本科及以上；扎实的 Java 基础，熟悉 Spring Boot；了解 MySQL、Redis；理解常见数据结构与算法；有微服务或分布式项目经历者优先。",
  },
  {
    id: "job-002",
    title: "前端开发工程师（校招）",
    company: "界面工场",
    category: "互联网研发",
    location: "北京",
    salary: "14-22K·13薪",
    experience: "应届",
    skills: ["JavaScript", "TypeScript", "React", "Vue", "HTML/CSS", "Webpack"],
    description:
      "负责 Web 前端产品的开发与优化；与设计、后端协作完成需求；持续优化页面性能与用户体验。要求：熟悉 HTML/CSS/JavaScript；掌握 React 或 Vue 之一；了解 TypeScript 与前端工程化；有完整项目作品或开源贡献者优先。",
  },
  {
    id: "job-003",
    title: "算法工程师-机器学习（校招）",
    company: "智深智能",
    category: "互联网研发",
    location: "深圳",
    salary: "25-40K·15薪",
    experience: "应届",
    skills: ["Python", "PyTorch", "机器学习", "深度学习", "数据挖掘", "NLP"],
    description:
      "负责推荐/搜索/NLP 等方向的算法研发与落地；跟进前沿论文并工程化。要求：硕士及以上，机器学习/统计相关；熟悉 Python 与 PyTorch；有扎实的机器学习理论基础；有顶会论文、竞赛获奖或实习项目者优先。",
  },
  {
    id: "job-004",
    title: "数据分析师（校招）",
    company: "数知未来",
    category: "互联网研发",
    location: "上海",
    salary: "12-20K·13薪",
    experience: "应届",
    skills: ["SQL", "Python", "数据分析", "Excel", "Tableau", "统计学"],
    description:
      "负责业务数据的提取、分析与可视化，输出数据报告支持决策；搭建和维护核心业务指标体系。要求：熟练 SQL；掌握 Python 或 R 做数据处理；熟悉常用统计方法；有较强的业务理解与表达能力；用过 Tableau/PowerBI 者优先。",
  },
  {
    id: "job-005",
    title: "测试开发工程师（校招）",
    company: "稳健软件",
    category: "互联网研发",
    location: "成都",
    salary: "12-18K·13薪",
    experience: "应届",
    skills: ["Python", "自动化测试", "Selenium", "接口测试", "Linux", "CI/CD"],
    description:
      "负责自动化测试框架的开发与维护；编写测试用例并执行；推动质量保障流程。要求：熟悉至少一门编程语言（Python/Java）；了解自动化测试与接口测试；熟悉 Linux 基本操作；有 CI/CD 经验者优先。",
  },
  {
    id: "job-006",
    title: "产品经理（校招）",
    company: "悦享互娱",
    category: "产品运营",
    location: "广州",
    salary: "13-20K·14薪",
    experience: "应届",
    skills: ["需求分析", "产品设计", "Axure", "数据分析", "项目管理", "竞品分析"],
    description:
      "负责产品需求调研、方案设计与功能落地；撰写 PRD 并跟进开发上线；分析数据驱动产品迭代。要求：逻辑清晰、有较强沟通能力；会用 Axure/墨刀 等原型工具；有产品实习或完整项目经历者优先。",
  },
  {
    id: "job-007",
    title: "用户运营实习生",
    company: "潮起社区",
    category: "产品运营",
    location: "北京",
    salary: "150-200元/天",
    experience: "实习",
    skills: ["用户运营", "活动策划", "数据分析", "社群运营", "内容运营", "Excel"],
    description:
      "协助用户增长与活跃运营；策划并执行线上活动；维护用户社群并收集反馈；输出运营数据复盘。要求：在校生，每周到岗 4 天以上；细心、有责任心；有社群或活动运营经验者优先。",
  },
  {
    id: "job-008",
    title: "新媒体运营实习生",
    company: "光年传媒",
    category: "产品运营",
    location: "上海",
    salary: "120-180元/天",
    experience: "实习",
    skills: ["内容运营", "文案", "短视频", "新媒体", "数据分析", "社交媒体"],
    description:
      "负责公众号/小红书/抖音等平台内容创作与发布；跟踪数据并优化内容；参与选题策划。要求：文字功底好、有网感；熟悉主流社交媒体平台；会基础图文/视频编辑者优先。",
  },
  {
    id: "job-009",
    title: "Java 后端实习生",
    company: "云启科技",
    category: "互联网研发",
    location: "杭州",
    salary: "180-260元/天",
    experience: "实习",
    skills: ["Java", "Spring", "MySQL", "Git", "数据结构", "算法"],
    description:
      "参与后端业务模块开发；在导师指导下完成接口开发与联调；编写单元测试。要求：在校生，掌握 Java 基础与面向对象；了解 Spring 与 MySQL；熟悉常见数据结构与算法；每周到岗 3 天以上。",
  },
  {
    id: "job-010",
    title: "前端开发实习生",
    company: "界面工场",
    category: "互联网研发",
    location: "远程",
    salary: "150-220元/天",
    experience: "实习",
    skills: ["JavaScript", "React", "HTML/CSS", "Git", "TypeScript"],
    description:
      "参与 Web 前端页面开发与组件封装；配合修复 bug 与样式还原。要求：在校生，熟悉 HTML/CSS/JS；了解 React；有 Git 使用经验；可远程稳定投入者优先。",
  },
  {
    id: "job-011",
    title: "市场营销专员（校招）",
    company: "鲜活快消",
    category: "其他行业",
    location: "深圳",
    salary: "8-12K·13薪",
    experience: "应届",
    skills: ["市场营销", "活动策划", "文案", "沟通", "Excel", "PPT"],
    description:
      "负责品牌市场活动的策划与执行；对接供应商与渠道；整理市场数据与营销复盘。要求：市场/营销/传播相关专业优先；有较强沟通与执行力；熟练 Office；有活动落地经验者优先。",
  },
  {
    id: "job-012",
    title: "财务分析实习生",
    company: "稳金资本",
    category: "其他行业",
    location: "上海",
    salary: "150-200元/天",
    experience: "实习",
    skills: ["财务分析", "Excel", "会计", "数据分析", "财务建模"],
    description:
      "协助财务报表整理与分析；参与预算与成本核算；制作财务分析模型与报告。要求：财会/金融相关专业在校生；Excel 熟练；了解基本财务知识；细致、严谨；每周到岗 4 天以上。",
  },
  {
    id: "job-013",
    title: "UI 设计师（校招）",
    company: "视觉派",
    category: "设计",
    location: "杭州",
    salary: "10-16K·13薪",
    experience: "应届",
    skills: ["Figma", "Sketch", "UI设计", "交互设计", "视觉设计", "原型"],
    description:
      "负责 App/Web 界面的视觉与交互设计；输出高保真原型与设计规范；与产品、研发协作还原。要求：设计相关专业；熟练 Figma/Sketch；有完整作品集；懂交互逻辑与设计规范者优先。",
  },
  {
    id: "job-014",
    title: "平面/视觉设计实习生",
    company: "光年传媒",
    category: "设计",
    location: "上海",
    salary: "130-180元/天",
    experience: "实习",
    skills: ["Photoshop", "Illustrator", "平面设计", "海报", "排版", "品牌设计"],
    description:
      "负责活动海报、运营物料、社媒配图等视觉设计；配合品牌做视觉延展。要求：熟练 PS/AI；有审美与排版能力；有作品集；每周到岗 3 天以上。",
  },
  {
    id: "job-015",
    title: "人力资源专员（校招）",
    company: "鼎才咨询",
    category: "人力资源",
    location: "北京",
    salary: "8-12K·13薪",
    experience: "应届",
    skills: ["招聘", "HR", "沟通", "Excel", "员工关系", "组织发展"],
    description:
      "负责招聘渠道维护与简历筛选、面试安排；协助员工入转调离与日常人事工作。要求：人力/管理/心理相关专业；亲和力强、沟通顺畅；熟练 Office；有 HR 实习经验者优先。",
  },
  {
    id: "job-016",
    title: "校园招聘实习生（HR）",
    company: "云启科技",
    category: "人力资源",
    location: "深圳",
    salary: "140-180元/天",
    experience: "实习",
    skills: ["招聘", "活动策划", "沟通", "Excel", "数据整理"],
    description:
      "协助校园招聘宣讲、笔面试组织与候选人沟通；维护招聘数据看板。要求：在校生，表达与组织能力强；细心负责；每周到岗 3-4 天。",
  },
  {
    id: "job-017",
    title: "销售管理培训生（校招）",
    company: "拓界科技",
    category: "销售",
    location: "广州",
    salary: "8-15K+提成",
    experience: "应届",
    skills: ["销售", "客户开发", "沟通谈判", "市场拓展", "CRM"],
    description:
      "负责 B 端客户开发与维护；完成销售目标；轮岗了解公司业务全流程。要求：不限专业；抗压、沟通能力强、目标感强；有销售或社团实践经历者优先。",
  },
  {
    id: "job-018",
    title: "客户成功专员（校招）",
    company: "云启科技",
    category: "销售",
    location: "杭州",
    salary: "9-14K·13薪",
    experience: "应届",
    skills: ["客户成功", "沟通", "数据分析", "SaaS", "客户关系"],
    description:
      "负责 SaaS 客户的开通、培训、续费与增购；跟踪客户健康度并推动价值实现。要求：沟通与同理心强；逻辑清晰；对 To B 业务有兴趣；有客户对接经验者优先。",
  },
  {
    id: "job-019",
    title: "初中/高中学科老师（校招）",
    company: "明德教育",
    category: "教育",
    location: "成都",
    salary: "10-18K·13薪",
    experience: "应届",
    skills: ["教学", "课程设计", "学科知识", "沟通表达", "班级管理"],
    description:
      "负责学科教学与备课、作业批改与学情跟踪；与家长沟通学生情况。要求：相关学科专业，有教师资格证优先；表达清晰、有耐心；有家教或带班经验者优先。",
  },
  {
    id: "job-020",
    title: "课程研发实习生",
    company: "明德教育",
    category: "教育",
    location: "武汉",
    salary: "120-160元/天",
    experience: "实习",
    skills: ["课程设计", "内容编写", "PPT", "教研", "资料整理"],
    description:
      "协助学科课程与讲义研发、题库整理；参与课件制作与教研活动。要求：在校生，学科基础扎实、文字能力强；细致；每周到岗 3 天以上。",
  },
  {
    id: "job-021",
    title: "供应链管理培训生（校招）",
    company: "鲜活快消",
    category: "供应链",
    location: "深圳",
    salary: "9-14K·13薪",
    experience: "应届",
    skills: ["供应链", "采购", "物流", "Excel", "数据分析", "计划"],
    description:
      "轮岗采购、计划、物流等模块；参与供应商管理与库存优化；用数据驱动供应链改善。要求：供应链/物流/管理相关；逻辑与数据能力强；熟练 Excel；有相关实习者优先。",
  },
  {
    id: "job-022",
    title: "电商运营实习生",
    company: "潮起社区",
    category: "产品运营",
    location: "广州",
    salary: "130-180元/天",
    experience: "实习",
    skills: ["电商运营", "数据分析", "活动策划", "选品", "Excel", "店铺管理"],
    description:
      "协助店铺日常运营、商品上下架与活动报名；分析销售数据并优化。要求：在校生，对电商有热情；细心、数据敏感；熟悉淘宝/抖音电商后台者优先。",
  },
  {
    id: "job-023",
    title: "客服专员（校招）",
    company: "悦享互娱",
    category: "客户服务",
    location: "成都",
    salary: "6-9K·13薪",
    experience: "应届",
    skills: ["客户服务", "沟通", "问题处理", "工单系统", "应变"],
    description:
      "负责用户在线/电话咨询的响应与问题处理；记录并跟进工单；收集用户反馈。要求：不限专业；表达清晰、有耐心与同理心；能适应轮班者优先。",
  },
  {
    id: "job-024",
    title: "行政人事助理（校招）",
    company: "鼎才咨询",
    category: "行政",
    location: "南京",
    salary: "6-9K·13薪",
    experience: "应届",
    skills: ["行政", "办公软件", "沟通协调", "活动组织", "档案管理"],
    description:
      "负责办公环境与日常行政事务、会议与活动组织、档案与考勤管理。要求：细心、条理性强；熟练 Office；亲和、服务意识强；有学生工作经验者优先。",
  },
  {
    id: "job-025",
    title: "运维开发工程师（校招）",
    company: "稳健软件",
    category: "互联网研发",
    location: "西安",
    salary: "13-20K·13薪",
    experience: "应届",
    skills: ["Linux", "Docker", "Kubernetes", "Shell", "监控", "CI/CD"],
    description:
      "负责服务部署、监控告警与稳定性保障；建设自动化运维工具。要求：熟悉 Linux 与网络基础；了解 Docker/K8s；会 Shell/Python 脚本；有云平台经验者优先。",
  },
  {
    id: "job-026",
    title: "测试工程师实习生",
    company: "稳健软件",
    category: "互联网研发",
    location: "远程",
    salary: "140-200元/天",
    experience: "实习",
    skills: ["功能测试", "用例设计", "Bug跟踪", "接口测试", "Postman"],
    description:
      "执行功能与回归测试、编写测试用例、提交并跟踪缺陷。要求：在校生，细心、逻辑清晰；了解测试基本流程；会 Postman 者优先；可远程稳定投入。",
  },
  {
    id: "job-027",
    title: "财务管理培训生（校招）",
    company: "稳金资本",
    category: "金融",
    location: "上海",
    salary: "10-16K·14薪",
    experience: "应届",
    skills: ["财务", "会计", "Excel", "财务分析", "审计", "CPA"],
    description:
      "轮岗会计核算、财务分析、资金等模块；参与月度结账与报表编制。要求：财会/金融相关；细致严谨；考过 CPA/ACCA 科目者优先。",
  },
  {
    id: "job-028",
    title: "投研分析实习生",
    company: "稳金资本",
    category: "金融",
    location: "北京",
    salary: "200-300元/天",
    experience: "实习",
    skills: ["行业研究", "财务建模", "数据分析", "Excel", "PPT", "Wind"],
    description:
      "协助行业与公司研究、搭建财务模型、撰写研究报告。要求：金融/经济/财会相关在校生；逻辑与数据能力强；会用 Wind/Excel 建模者优先；每周到岗 4 天以上。",
  },
  {
    id: "job-029",
    title: "内容编辑/文案（校招）",
    company: "光年传媒",
    category: "内容创作",
    location: "杭州",
    salary: "8-13K·13薪",
    experience: "应届",
    skills: ["文案", "内容策划", "写作", "选题", "新媒体", "SEO"],
    description:
      "负责品牌与产品相关图文内容的策划与撰写；优化标题与传播效果。要求：中文/新闻/传播相关优先；文笔好、有网感；有公众号/自媒体作品者优先。",
  },
  {
    id: "job-030",
    title: "短视频编导实习生",
    company: "潮起社区",
    category: "内容创作",
    location: "上海",
    salary: "150-200元/天",
    experience: "实习",
    skills: ["短视频", "脚本", "剪辑", "Premiere", "策划", "拍摄"],
    description:
      "参与短视频选题、脚本、拍摄与剪辑全流程；跟踪数据优化内容。要求：在校生，懂短视频玩法；会 Pr/剪映；有作品者优先；每周到岗 3 天以上。",
  },
  {
    id: "job-031",
    title: "Python 数据开发实习生",
    company: "数知未来",
    category: "互联网研发",
    location: "深圳",
    salary: "180-260元/天",
    experience: "实习",
    skills: ["Python", "SQL", "ETL", "数据仓库", "Pandas", "Airflow"],
    description:
      "参与数据采集、清洗与 ETL 开发；维护数据仓库与报表。要求：在校生，熟悉 Python 与 SQL；了解数据处理流程；用过 Pandas 者优先；每周到岗 4 天。",
  },
  {
    id: "job-032",
    title: "产品运营实习生",
    company: "云启科技",
    category: "产品运营",
    location: "成都",
    salary: "130-180元/天",
    experience: "实习",
    skills: ["产品运营", "数据分析", "用户调研", "活动策划", "Excel"],
    description:
      "协助产品功能推广、用户调研与数据复盘；参与运营活动策划执行。要求：在校生，逻辑清晰、数据敏感；有运营或产品兴趣；每周到岗 3-4 天。",
  },
  {
    id: "job-033",
    title: "Android 开发工程师（校招）",
    company: "界面工场",
    category: "互联网研发",
    location: "北京",
    salary: "15-24K·14薪",
    experience: "应届",
    skills: ["Kotlin", "Java", "Android", "Jetpack", "性能优化"],
    description:
      "负责 Android 客户端功能开发与性能优化；与产品设计协作迭代。要求：熟悉 Kotlin/Java 与 Android 体系；了解 Jetpack；有 App 项目或作品者优先。",
  },
  {
    id: "job-034",
    title: "iOS 开发工程师（校招）",
    company: "界面工场",
    category: "互联网研发",
    location: "深圳",
    salary: "15-24K·14薪",
    experience: "应届",
    skills: ["Swift", "Objective-C", "iOS", "UIKit", "性能优化"],
    description:
      "负责 iOS 客户端开发与体验优化；参与架构演进。要求：熟悉 Swift；了解 UIKit/SwiftUI；有上架 App 或开源项目者优先。",
  },
  {
    id: "job-035",
    title: "医药信息专员（校招）",
    company: "济世医药",
    category: "医疗健康",
    location: "南京",
    salary: "9-14K·13薪",
    experience: "应届",
    skills: ["医学知识", "沟通", "学术推广", "客户维护", "PPT"],
    description:
      "负责向医院/医生进行产品学术推广与信息传递；维护客户关系。要求：医药/生物/护理相关专业；沟通表达强；有学术或销售实践者优先。",
  },
  {
    id: "job-036",
    title: "临床数据管理实习生",
    company: "济世医药",
    category: "医疗健康",
    location: "上海",
    salary: "150-200元/天",
    experience: "实习",
    skills: ["数据管理", "Excel", "医学统计", "SAS", "细致"],
    description:
      "协助临床试验数据的录入、核查与整理；参与数据库维护。要求：医学/统计/生物相关在校生；细致严谨；了解医学统计或 SAS 者优先；每周到岗 4 天。",
  },
  {
    id: "job-037",
    title: "品牌市场实习生",
    company: "鲜活快消",
    category: "市场营销",
    location: "广州",
    salary: "130-170元/天",
    experience: "实习",
    skills: ["品牌", "市场活动", "文案", "社媒", "PPT", "数据分析"],
    description:
      "协助品牌营销活动的策划与落地、社媒内容维护与数据整理。要求：在校生，有创意与执行力；熟练 Office；对消费品牌有热情者优先。",
  },
  {
    id: "job-038",
    title: "游戏策划实习生",
    company: "悦享互娱",
    category: "产品运营",
    location: "成都",
    salary: "150-220元/天",
    experience: "实习",
    skills: ["游戏策划", "数值", "文案", "Excel", "玩法设计"],
    description:
      "参与游戏玩法/数值/文案策划与文档撰写；跟进功能落地与测试。要求：在校生，热爱游戏、逻辑清晰；会用 Excel 做数值；有 Demo 或设计作品者优先。",
  },
  {
    id: "job-039",
    title: "大数据开发工程师（校招）",
    company: "数知未来",
    category: "互联网研发",
    location: "杭州",
    salary: "18-30K·15薪",
    experience: "应届",
    skills: ["Java", "Scala", "Spark", "Flink", "Hadoop", "Kafka"],
    description:
      "负责大数据平台与实时/离线计算任务开发；优化数据链路性能。要求：熟悉 Java/Scala；了解 Spark/Flink 之一；理解分布式与数仓；有相关项目者优先。",
  },
  {
    id: "job-040",
    title: "法务专员（校招）",
    company: "鼎才咨询",
    category: "法务",
    location: "北京",
    salary: "10-16K·13薪",
    experience: "应届",
    skills: ["合同审核", "法律", "合规", "风险管理", "文书"],
    description:
      "负责合同审查与起草、合规咨询与风险提示；协助处理法律事务。要求：法学专业，已过法考者优先；严谨、文字能力强；有律所或企业法务实习者优先。",
  },
];
